name: Build and Deploy

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    name: Build Docker Image and Update ECS Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build artifact with Maven
        run: mvn clean package

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t 737432160967.dkr.ecr.eu-north-1.amazonaws.com/ctse:latest .
          docker tag ctse:latest 737432160967.dkr.ecr.eu-north-1.amazonaws.com/ctse:latest

      - name: Push Docker image to ECR
        run: docker push 737432160967.dkr.ecr.eu-north-1.amazonaws.com/ctse:latest

      - name: Update ECS Service
        run: |
          aws ecs update-service --cluster ctseCluster --service ctseService --force-new-deployment